name: insects of the earth
favicon: null
layout_spectrum: 0.34251059242524207
typography_spectrum: 0.31659214827232063
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.2003149762749672
  lightness: 0.5344015988521278
  saturation: 0.16649451106786728
  rhythmicContrast: 0.9373421559575945
purpose: []
